//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBase.Off.Website.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeBase.Off.Website.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات پشتیبان گیری از اطلاعات به اتمام رسید. (نام فایل: {0}).
        /// </summary>
        internal static string Messages_BackupComplete {
            get {
                return ResourceManager.GetString("Messages_BackupComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در روند اجرای عملیات پشتیبان گیری از اطلاعات خطایی رخ داده است..
        /// </summary>
        internal static string Messages_BackupFailure {
            get {
                return ResourceManager.GetString("Messages_BackupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_DuplicateSlug {
            get {
                return ResourceManager.GetString("Messages_DuplicateSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_Error403 {
            get {
                return ResourceManager.GetString("Messages_Error403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_Error403Description {
            get {
                return ResourceManager.GetString("Messages_Error403Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_Error404 {
            get {
                return ResourceManager.GetString("Messages_Error404", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_Error404Description {
            get {
                return ResourceManager.GetString("Messages_Error404Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_Error500 {
            get {
                return ResourceManager.GetString("Messages_Error500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_Error500Description {
            get {
                return ResourceManager.GetString("Messages_Error500Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی آدرس ایمیل رو درست وارد کردی؟ (با www شروع نمیشه، مثلا: me@gmail.com).
        /// </summary>
        internal static string Messages_InvalidEmail {
            get {
                return ResourceManager.GetString("Messages_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای &quot;{0}&quot; یه مقدار عددی و مثبت وارد کن!.
        /// </summary>
        internal static string Messages_InvalidInteger {
            get {
                return ResourceManager.GetString("Messages_InvalidInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول &quot;{0}&quot; از {1} حرف بیشتر شده! کمش کن چه خبرته؟.
        /// </summary>
        internal static string Messages_InvalidMaxLength {
            get {
                return ResourceManager.GetString("Messages_InvalidMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول &quot;{0}&quot; باید بین {1} و {2} کاراکتر باشه! همینطوره؟.
        /// </summary>
        internal static string Messages_InvalidMinMaxLength {
            get {
                return ResourceManager.GetString("Messages_InvalidMinMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه مشخص شده معتبر نمی باشد..
        /// </summary>
        internal static string Messages_InvalidOpenIdIdentifier {
            get {
                return ResourceManager.GetString("Messages_InvalidOpenIdIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_InvalidParameter {
            get {
                return ResourceManager.GetString("Messages_InvalidParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقداری که واسه &quot;{0}&quot; وارد می کنی فقط میتونه شامل کاراکترهای A تا Z، اعداد و - باشه!.
        /// </summary>
        internal static string Messages_InvalidSlug {
            get {
                return ResourceManager.GetString("Messages_InvalidSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطمئنی آدرس اینترنتی رو درست وارد کردی؟ (مثلا: http://www.codebase.ir).
        /// </summary>
        internal static string Messages_InvalidUrl {
            get {
                return ResourceManager.GetString("Messages_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_OpenIdConnectionFailure {
            get {
                return ResourceManager.GetString("Messages_OpenIdConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_OpenIdLoginFailure {
            get {
                return ResourceManager.GetString("Messages_OpenIdLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_OpenIdLoginSuccess {
            get {
                return ResourceManager.GetString("Messages_OpenIdLoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Messages_OpenIdLogoutSuccess {
            get {
                return ResourceManager.GetString("Messages_OpenIdLogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; رو وارد نکردی!.
        /// </summary>
        internal static string Messages_Required {
            get {
                return ResourceManager.GetString("Messages_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامتون رو دریافت کردیم. لطفا منتظر پاسخ ما باشین. سعی می کنیم در اسرع وقت باهاتون تماس بگیریم. مرسی :).
        /// </summary>
        internal static string Messages_SendMessageComplete {
            get {
                return ResourceManager.GetString("Messages_SendMessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مثل اینکه توی ارسال پیامتون مشکلی پیش اومده! پوزش مارو بپذیرین و مجددا تلاش کنید. باز هم بخاطر مشکل پیش اومده متاسفیم..
        /// </summary>
        internal static string Messages_SendMessageFailure {
            get {
                return ResourceManager.GetString("Messages_SendMessageFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string Texts_False {
            get {
                return ResourceManager.GetString("Texts_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعلوم.
        /// </summary>
        internal static string Texts_NotSpecified {
            get {
                return ResourceManager.GetString("Texts_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        internal static string Texts_True {
            get {
                return ResourceManager.GetString("Texts_True", resourceCulture);
            }
        }
    }
}
